insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('Carlos', 'Acevedo', 'DNI', 34123478, 'carlosg@gmail.com', 'ROL_CAMIONERO', 'San Lorenzo', 1276, 1, 'A', 'mecanico154', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('Pedro', 'Cabrera', 'DNI', 28173464, 'pedritocabrera@gmail.com', 'ROL_CAMIONERO', 'José Ingenieros', 2547, 'ing464', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('Jesús', 'Olivos', 'DNI', 19765384, 'olivosjesus@gmail.com', 'ROL_CAMIONERO', 'Montevideo', 417, 8, 'C', 'fierrero46', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('Luis', 'Salinas', 'DNI', 21847033, 'salinasluismecanico@hotmail.com', 'ROL_CAMIONERO', 'Av. Pellegrini', 3126, 'password123', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('Miguel', 'Pedraza', 'DNI', 36482529, 'miguelped@gmail.com', 'ROL_CAMIONERO', 'Córdoba', 1295, 3, 'B', 'pedmig529', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('Andrés', 'López', 'DNI', 34127403, 'andreslopez23@gmail.com', 'ROL_CAMIONERO', 'Sarmiento', 4572, 7, 'C', 'andy123', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('Hernán', 'Valero', 'DNI', 22796284, 'hernanmartinvalero@gmail.com', 'ROL_CAMIONERO', 'San Juan', 648, 'rosariocentral1889', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('Diego', 'Serra', 'DNI', 38741369, 'dieguito10serra@hotmail.com', 'ROL_CAMIONERO', 'Entre Ríos', 814, 'bpx843', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('Alberto', 'Torres', 'DNI', 20946273, 'torrestito@yahoo.com', 'ROL_CAMIONERO', 'Ocampos', 2248, 4, 'D', 'taller2248', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('José', 'Giménez', 'DNI', 35852147, 'jose.gimenez@gmail.com', 'ROL_CAMIONERO', 'Urquiza', 3394, 5, 'E', 'josgim875', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('Jimena', 'Escudero', 'DNI', 40129402, 'jime.escudero7@gmail.com', 'ROL_ADMINISTRATIVO', 'Balcarce', 1542, 2, 'A', 'jime_129402', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, floor, department, password, is_deleted)  values  ('Fernando', 'Bernal', 'DNI', 42673981, 'bernalfernando12@gmail.com', 'ROL_ADMINISTRATIVO', 'Mitre', 2743, 1, 'B', 'cabj2743', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('admin', 'admin', 'DNI', 12123123, 'admin.user@gmail.com', 'ROL_ADMIN', 'admin', 123, 'adminuser123', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('Juan Carlos', 'Gonzalez', 'DNI', 366280281, 'admin@taller4.com', 'ROL_ADMIN', 'Wallaby', 42, '$2a$10$3MqrebYGnaEN80tCNr2t2ue4x9BGU1UJZx5nMfq.pIjf1QvPCq8pS', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('Miguel', 'Serra', 'DNI', 366280282, 'administrativo@taller4.com', 'ROL_ADMINISTRATIVO', 'Wallaby', 42, '$2a$10$0CeMPGGi2Dvh1/knAowCiucWhjPsoneJ4kv.ezrSNYX0kTir7jwz6', false);
insert into empleado (nombre, apellido, category, identification_number, email, role, street, number, password, is_deleted)  values  ('Lucas', 'Torres', 'DNI', 366280283, 'mecanico@taller4.com', 'ROL_CAMIONERO', 'Wallaby', 42, '$2a$10$RL1NLb.67XpVCTfkJok7ouQKK.mHjmL73/N/IKhyzokzBLv6P6sra', false);

insert into ciudad (nombre, provincia, is_deleted) values ('La Plata', 'BUENOS_AIRES', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Mar del Plata', 'BUENOS_AIRES', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Bahía Blanca', 'BUENOS_AIRES', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Rosario', 'SANTA_FE', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Santa Fe', 'SANTA_FE', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Rafaela', 'SANTA_FE', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Córdoba', 'CORDOBA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Villa María', 'CORDOBA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Mendoza', 'MENDOZA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('San Rafael', 'MENDOZA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('San Juan', 'SAN_JUAN', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Concordia', 'ENTRE_RIOS', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Paraná', 'ENTRE_RIOS', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Resistencia', 'CHACO', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Formosa', 'FORMOSA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('San Salvador de Jujuy', 'JUJUY', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Catamarca', 'CATAMARCA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Neuquén', 'NEUQUEN', false);
insert into ciudad (nombre, provincia, is_deleted) values ('San Martín de los Andes', 'NEUQUEN', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Tucumán', 'TUCUMAN', false);
insert into ciudad (nombre, provincia, is_deleted) values ('San Miguel de Tucumán', 'TUCUMAN', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Salta', 'SALTA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Orán', 'SALTA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Viedma', 'RIO_NEGRO', false);
insert into ciudad (nombre, provincia, is_deleted) values ('San Carlos de Bariloche', 'RIO_NEGRO', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Ushuaia', 'TIERRA_DEL_FUEGO', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Puerto Madryn', 'CHUBUT', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Comodoro Rivadavia', 'CHUBUT', false);
insert into ciudad (nombre, provincia, is_deleted) values ('La Rioja', 'LA_RIOJA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Santa Rosa', 'LA_PAMPA', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Rio Gallegos', 'SANTA_CRUZ', false);
insert into ciudad (nombre, provincia, is_deleted) values ('Punta Arenas', 'SANTA_CRUZ', false);

insert into payment_type (name, category, is_deleted) values ('Visa', 'DEBIT_CARD', false);
insert into payment_type (name, category, is_deleted) values ('Visa', 'CREDIT_CARD', false);
insert into payment_type (name, category, is_deleted) values ('Mastercard', 'DEBIT_CARD', false);
insert into payment_type (name, category, is_deleted) values ('Mastercard', 'CREDIT_CARD', false);
insert into payment_type (name, category, is_deleted) values ('American Express', 'CREDIT_CARD', false);
insert into payment_type (name, category, is_deleted) values ('Efectivo', 'OTHER', false);
insert into payment_type (name, category, is_deleted) values ('Transferencia', 'OTHER', false);

insert into tipo_carga (nombre, is_deleted) values ('Alimentos', false);
insert into tipo_carga (nombre, is_deleted) values ('Tecnología', false);
insert into tipo_carga (nombre, is_deleted) values ('Muebles', false);
insert into tipo_carga (nombre, is_deleted) values ('Ropa', false);
insert into tipo_carga (nombre, is_deleted) values ('Farmacéuticos', false);
insert into tipo_carga (nombre, is_deleted) values ('Bebidas', false);
insert into tipo_carga (nombre, is_deleted) values ('Herramientas', false);
insert into tipo_carga (nombre, is_deleted) values ('Electrónica', false);
insert into tipo_carga (nombre, is_deleted) values ('Textiles', false);
insert into tipo_carga (nombre, is_deleted) values ('Productos perecederos', false);
insert into tipo_carga (nombre, is_deleted) values ('Cosméticos', false);
insert into tipo_carga (nombre, is_deleted) values ('Juguetes', false);
insert into tipo_carga (nombre, is_deleted) values ('Artículos de festejo', false);
insert into tipo_carga (nombre, is_deleted) values ('Automóviles', false);
insert into tipo_carga (nombre, is_deleted) values ('Maquinaria', false);
insert into tipo_carga (nombre, is_deleted) values ('Animales', false);
insert into tipo_carga (nombre, is_deleted) values ('Vehículos', false);

insert into carga (nombre, tipo_carga_id, is_deleted) values ('Naranjas de Tucumán', 10, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Soja en grano', 1, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Electrodomésticos importados', 8, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Herramientas para construcción', 7, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Vino Malbec de Mendoza', 6, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Remeras y jeans nacionales', 4, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Camas y colchones', 3, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Computadoras para escuelas', 2, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Vacunas y medicamentos', 5, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Carne vacuna enfriada', 10, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Productos de perfumería', 11, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Pelotas y juegos didácticos', 12, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Decoraciones para Navidad', 13, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Automóviles nuevos', 14, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Tractores agrícolas', 15, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Terneros para cría', 16, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Camiones utilitarios', 17, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Yerba mate envasada', 1, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Celulares ensamblados en Tierra del Fuego', 2, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Heladeras y lavarropas', 8, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Ladrillos y cemento', 7, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Sidra y pan dulce', 6, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Sábanas y frazadas', 9, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Verduras frescas del AMBA', 10, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Productos de limpieza', 11, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Ropa de invierno', 4, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Muebles de madera de Misiones', 3, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Tablets para programa Conectar Igualdad', 2, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Panificados de industria local', 1, false);
insert into carga (nombre, tipo_carga_id, is_deleted) values ('Animales de granja vivos', 16, false);

insert into marca (nombre, is_deleted) values ('Mercedes-Benz', false);
insert into marca (nombre, is_deleted) values ('Volvo', false);
insert into marca (nombre, is_deleted) values ('Scania', false);
insert into marca (nombre, is_deleted) values ('MAN', false);
insert into marca (nombre, is_deleted) values ('Iveco', false);
insert into marca (nombre, is_deleted) values ('Ford', false);
insert into marca (nombre, is_deleted) values ('DAF', false);
insert into marca (nombre, is_deleted) values ('Renault', false);
insert into marca (nombre, is_deleted) values ('Hino', false);
insert into marca (nombre, is_deleted) values ('Freightliner', false);
insert into marca (nombre, is_deleted) values ('Volkswagen', false);

insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('ABC123', '5', 'Stralis', 2014, 450000, 'ch00123abc', 'mo00123abc', 'Revisión completa en 2023', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('DEF456', '1', 'Actros', 2020, 300000, 'ch00456def', 'mo00456def', 'En excelente estado', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('GHI789', '3', 'R500', 2019, 380000, 'ch00789ghi', 'mo00789ghi', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('JKL321', '11', 'Constellation', 2013, 510000, 'ch00321jkl', 'mo00321jkl', 'Necesita cambio de neumáticos', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('MNO654', '5', 'Tector', 2012, 600000, 'ch00654mno', 'mo00654mno', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('PQ123RS', '6', 'Cargo', 2021, 220000, 'ch00987pqr', 'mo00987pqr', 'Uso exclusivo para transporte refrigerado', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('ST456UV', '1', 'Axor', 2018, 430000, 'ch00246stu', 'mo00246stu', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('VW135XZ', '3', 'P360', 2020, 280000, 'ch00135vwx', 'mo00135vwx', 'Último service en enero 2025', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('YA864LB', '2', 'FH540', 2019, 390000, 'ch00864yza', 'mo00864yza', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('BCD975', '1', 'Atego', 2011, 650000, 'ch00975bcd', 'mo00975bcd', 'Presenta desgaste en suspensión', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('EFG246', '5', 'Stralis', 2014, 500000, 'ch00246efg', 'mo00246efg', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('HI357JK', '6', 'Cargo', 2022, 150000, 'ch00357hij', 'mo00357hij', 'Nuevo en flota', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('KLM468', '2', 'FH460', 2013, 470000, 'ch00468klm', 'mo00468klm', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('NO579CD', '3', 'R410', 2021, 260000, 'ch00579nop', 'mo00579nop', 'Apto para larga distancia', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('QR680AZ', '11', 'Delivery', 2019, 340000, 'ch00680qrs', 'mo00680qrs', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('TV791MN', '5', 'Tector', 2020, 310000, 'ch00791tuv', 'mo00791tuv', 'Servicio técnico reciente', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('WXY902', '1', 'Axor', 2013, 580000, 'ch00902wxy', 'mo00902wxy', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('ZAB013', '6', 'Cargo', 2012, 700000, 'ch00013zab', 'mo00013zab', 'Próximo a ser dado de baja', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('CD124FG', '3', 'P280', 2018, 460000, 'ch00124cde', 'mo00124cde', '', false);
insert into camion (patente, marca_id, modelo, anio, km, numero_chasis, numero_motor, observaciones, is_deleted) values ('FG235HJ', '2', 'FM370', 2021, 240000, 'ch00235fgh', 'mo00235fgh', 'En garantía hasta 2026', false);

insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30712345017, 'contacto@granjaelombligo.com', 'Granja El Ombligo SA', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30599876124, 'ventas@pereztech.com', 'Pérez Tecnología Argentina SRL', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30756783219, 'info@lopezmuebles.com.ar', 'Muebles López SA', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30678945211, 'contacto@modaviva.com', 'Moda Viva SA', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30823456789, 'info@farmaciafernandez.com', 'Farmacia Fernandez', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30612345677, 'bebidas@maraluna.com', 'Maraluna Bebidas SA', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30788812345, 'herramientas@elgalpon.com.ar', 'El Galpón Herramientas', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30567891234, 'ventas@sosaelectro.com', 'Electrodomésticos Sosa', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30790123456, 'textiles@fabricasantafe.com', 'Fábrica Textil Santa Fe', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30834567213, 'perecederos@bentierra.com', 'Bentierra Alimentos', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30733445566, 'cosmeticos@bellezanatural.com.ar', 'Belleza Natural', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30665432109, 'juguetes@dinojuguetes.com', 'Dino Juguetes SRL', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30544556677, 'ventas@autopartesdelnorte.com', 'Autopartes Del Norte SA', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30811223344, 'maquinaria@agrovera.com', 'Agro Vera Maquinaria', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30677788899, 'animales@veterinariaelcampo.com', 'Veterinaria El Campo', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30887654321, 'ventas@vehiculosurbanos.com', 'Vehículos Urbanos SA', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30700011223, 'ropa@modaarias.com', 'Noda Arias SRL', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30712345678, 'articulos@cotillonmilcolores.com', 'Cotillón Mil Colores', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30699887766, 'repuestos@nuñezautopartes.com', 'Nuñez Autopartes', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30845678901, 'helados@heladosvazquez.com.ar', 'Helados Vásquez SA', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30555443322, 'alimentacion@riosnatural.com', 'Rios Natural Alimentos', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30876543210, 'ventas@pintureriamolina.com', 'Pinturería Molina', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30733322211, 'materiales@ortegaconstruye.com', 'Ortega Construcciones', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ( 'CUIT', 30832145678, 'panificados@cabrerapan.com', 'Panificados Cabrera', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30744112233, 'informes@salazarpesca.com.ar', 'Salazar Pesca SRL', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30611122233, 'decoracion@casarios.com', 'Casa Rios Decoración', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30876598765, 'papeleria@torrespapel.com', 'Papelería Torres', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30665498732, 'zapatos@santanashoes.com', 'Santana Shoes', false);
insert into cliente (category, identification_number, email, business_name, is_deleted) values ('CUIT', 30756987412, 'distribucion@lacteosrivas.com.ar', 'Lácteos Rivas', false);

insert into viaje (cliente_id, camion_id, empleado_id, precio, carga_id, fecha_salida, fecha_estimada_entrega, estado, pago_id) values (1, 3, 1, 20000.00, 2, '2024-04-10', NULL, 'TO_DO', NULL);